### ISSUE TITLE
cache weaviate client

### ISSUE THREAD

**Issue by jhrozek** [stacklok/codegate#217]
We seem to be creating a weaviate client every time we want to use weaviate. I'm not sure this is needed, we could either just keep a persistent connection open or at least have the client opened and open/close the connection.

The reason is that even creating the client takes about a second and this slows down the conversation.

**Comment by lukehinds** [comment]
@ptelang , is this still active work?

**Comment by ptelang** [comment]
This issue was addressed earlier. Unlike earlier, the weaviate client is not created every time when codegate needs to use it. 

The HTTP call you mentioned above is a different issue. I am investigating why weaviate needs to make this http call.
