### ISSUE TITLE
Verify codegate works with Free CoPilot License

### ISSUE THREAD

**Issue by lukehinds** [stacklok/codegate#415]
CoPilot is now free, we should verify codegate works with this,  by looking at the pe-proxy header and see what URL is used. 

https://github.blog/news-insights/product-news/github-copilot-in-vscode-free/

**Comment by jhrozek** [comment]
Based on today's testing - in general the free copilot license appears to be using the same endpoints as the individual license. Interenstingly, even though the free license offers OpenAI and Anthropic, all the messages are in OpenAI format.

- [ ] OpenAI: chat in general
- [ ] OpenAI: detecting malicious packages in chat in natural language
- [ ] OpenAI: Obfuscating and reporting secrets in chat
- [ ] OpenAI: detecting and evaluating packages in output snippets
- [ ] OpenAI: FIM in general
- [ ] OpenAI: Obfuscating and reporting secrets in FIM

- [ ] Anthropic: chat in general
- [ ] Anthropic: Obfuscating and reporting secrets in chat
- [ ] Anthropic: detecting and evaluating packages in output snippets
- [ ] Anthropic: FIM in general
- [ ] Anthropic: Obfuscating and reporting secrets in FIM

This does not work according to my testing:
- [ ] Anthropic: detecting malicious packages in chat in natural language - it seems that we fail to detect the package ecosystem. Looking into this.

**Comment by jhrozek** [comment]
Reminder to test tomorrow: The different context menus (fix with copilot, review, explain, ....)

**Comment by lukehinds** [comment]
thanks @jhrozek
